### PR TITLE
Delete OBC storage class on delete system

### LINKED ISSUE #631: NSFS: Noobaa SC not deleted during uninstall
### Environment info
- NooBaa Version: master-20210428-nsfs 
- Platform: OCP 4.6.16

### Actual behavior
1. noobaa SC "noobaa.noobaa.io" is not deleted post uninstall of noobaa code via "noobaa uninstall --cleanup=true"

### Expected behavior
1. noobaa SC "noobaa.noobaa.io" should get deleted

### Steps to reproduce
1. Install noobaa code from dockerhub. 
2. Attempt uninstall using step "noobaa uninstall --cleanup=true"
3. "oc get sc -A" would show o/p as below. 

### More information - Screenshots / Logs / Other output

--------
[root@ocp-akshat-1-inf akshat]# noobaa uninstall --cleanup=true
ERRO[0000] Error discovered: the server is currently unable to handle the request 
INFO[0000] CLI version: 5.8.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210428-nsfs 
INFO[0000] operator-image: noobaa/noobaa-operator:master-20210428-nsfs 
INFO[0000] noobaa-db-image: centos/mongodb-36-centos7   
INFO[0000] Namespace: noobaa                            
INFO[0000]                                              
INFO[0000] System Delete:                               
INFO[0000] ✅ Exists: NooBaa "noobaa"                    
INFO[0000] Notice: Deletion of External secrets should be preformed manually 
INFO[0001] Deleting All object buckets in namespace "noobaa" 
INFO[0001] ✅ Updated:  "noobaa"                         
INFO[0001] 🗑️  Deleting:  "noobaa"                      
INFO[0001] 🗑️  Deleted :  "noobaa"                      
INFO[0001] 🗑️  Deleting: PersistentVolumeClaim "db-noobaa-db-0" 
INFO[0015] 🗑️  Deleted : PersistentVolumeClaim "db-noobaa-db-0" 
INFO[0015]                                              
INFO[0015] Operator Delete:                             
INFO[0015] 🗑️  Deleting: Deployment "noobaa-operator"   
INFO[0015] 🗑️  Deleted : Deployment "noobaa-operator"   
INFO[0015] 🗑️  Deleting: SecurityContextConstraints "noobaa-endpoint" 
INFO[0015] 🗑️  Deleted : SecurityContextConstraints "noobaa-endpoint" 
INFO[0015] 🗑️  Deleting: SecurityContextConstraints "noobaa" 
INFO[0015] 🗑️  Deleted : SecurityContextConstraints "noobaa" 
INFO[0015] 🗑️  Deleting: ClusterRoleBinding "noobaa.noobaa.io" 
INFO[0015] 🗑️  Deleted : ClusterRoleBinding "noobaa.noobaa.io" 
INFO[0015] 🗑️  Deleting: ClusterRole "noobaa.noobaa.io" 
INFO[0015] 🗑️  Deleted : ClusterRole "noobaa.noobaa.io" 
INFO[0015] 🗑️  Deleting: RoleBinding "noobaa-endpoint"  
INFO[0015] 🗑️  Deleted : RoleBinding "noobaa-endpoint"  
INFO[0015] 🗑️  Deleting: RoleBinding "noobaa"           
INFO[0015] 🗑️  Deleted : RoleBinding "noobaa"           
INFO[0015] 🗑️  Deleting: Role "noobaa-endpoint"         
INFO[0015] 🗑️  Deleted : Role "noobaa-endpoint"         
INFO[0015] 🗑️  Deleting: Role "noobaa"                  
INFO[0015] 🗑️  Deleted : Role "noobaa"                  
INFO[0016] 🗑️  Deleting: ServiceAccount "noobaa-endpoint" 
INFO[0016] 🗑️  Deleted : ServiceAccount "noobaa-endpoint" 
INFO[0016] 🗑️  Deleting: ServiceAccount "noobaa"        
INFO[0016] 🗑️  Deleted : ServiceAccount "noobaa"        
INFO[0016] Namespace Delete:                            
INFO[0016] 🗑️  Deleting: Namespace "noobaa"             
INFO[1113] 🗑️  Deleted : Namespace "noobaa"             
INFO[1113]                                              
INFO[1113] CRD Delete:                                  
INFO[1113] 🗑️  Deleting: CustomResourceDefinition "noobaas.noobaa.io" 
INFO[1114] 🗑️  Deleted : CustomResourceDefinition "noobaas.noobaa.io" 
INFO[1114] 🗑️  Deleting: CustomResourceDefinition "backingstores.noobaa.io" 
INFO[1115] 🗑️  Deleted : CustomResourceDefinition "backingstores.noobaa.io" 
INFO[1115] 🗑️  Deleting: CustomResourceDefinition "namespacestores.noobaa.io" 
INFO[1116] 🗑️  Deleted : CustomResourceDefinition "namespacestores.noobaa.io" 
INFO[1116] 🗑️  Deleting: CustomResourceDefinition "bucketclasses.noobaa.io" 
INFO[1117] 🗑️  Deleted : CustomResourceDefinition "bucketclasses.noobaa.io" 
INFO[1117] 🗑️  Deleting: CustomResourceDefinition "objectbucketclaims.objectbucket.io" 
INFO[1117] 🗑️  Deleted : CustomResourceDefinition "objectbucketclaims.objectbucket.io" 
INFO[1117] 🗑️  Deleting: CustomResourceDefinition "objectbuckets.objectbucket.io" 
INFO[1118] 🗑️  Deleted : CustomResourceDefinition "objectbuckets.objectbucket.io" 
[root@ocp-akshat-1-inf akshat]# 

[root@ocp-akshat-1-inf akshat]# oc get sc -A
NAME                             PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibm-spectrum-scale-csi-fileset   spectrumscale.csi.ibm.com      Delete          Immediate              false                  12d
ibm-spectrum-scale-internal      kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  12d
**noobaa.noobaa.io                 noobaa.noobaa.io/obc           Delete          Immediate              false                  10d**

--------

I don't have logs available at the moment. If logs are required, would have to recreate it, so kindly let me know.

### PR DESCRIPTION
**Pull request by romayalon**
Signed-off-by: Romy <romy2232@gmail.com>

1. deletes OBC storageclass on CLI uninstall/system delete or regular deletion of noobaa CR.
2. Fixed #631

### CODE REVIEW

File: pkg/util/util.go [hunk 1]
```diff
@@ -1579,3 +1580,16 @@ func writeCrtsToFile(secretName string, namespace string, secretValue []byte, en
 	}
 	return envVarValue, nil
 }
+
+// DeleteStorageClass deletes storage class
+func DeleteStorageClass(sc *storagev1.StorageClass) error{
+	log.Infof("start deleting storageclass %v", sc.Name)
+	if KubeCheck(sc) {
```
Comment (dannyzaken) [inline pkg/util/util.go:1587]: why do we need to kubecheck before deletion, why not just deleting?

**Review by dannyzaken — APPROVED** [review]

File: pkg/util/util.go (hunk 1 above)
Comment (romayalon) [reply pkg/util/util.go]: deleted kubecheck call, thanks
