### PR TITLE
return non-zero exit code on error

### LINKED ISSUE #77: When bucketclass create failed because we gave it a flag with no parameters the exit status is 0.
When bucketclass create failed because i gave it a flag with no parameters the exit status is 0.

$ build/_output/bin/noobaa-operator-local -n liran --operator-image noobaa/noobaa-operator:2.0.1-rc.1 bucketclass create --backingstores
Error: flag needs an argument: --backingstores

Options:
      --backingstores=[]: Set first tier backing stores (use commas or multiple flags)
      --placement='': Set first tier placement policy - Mirror | Spread | "" (empty defaults to single backing store)

Usage:
  noobaa bucketclass create <bucket-class-name> [flags] [options]

Use "noobaa options" for a list of global command-line options (applies to all commands).

$ echo $?
0

### PR DESCRIPTION
**Pull request by dannyzaken**
Fixes #77

### CODE REVIEW

**Comment by dannyzaken** [comment]
but `Execute()` is called in main, `cli.go` only returns the command. am I missing something?

**Comment by dannyzaken** [comment]
> I want the main to be a one liner.

I think that in go four liner is the new one liner 🤷‍♂

File: pkg/cli/cli.go [hunk 1]
```diff
@@ -46,6 +47,14 @@ const ASCIILogo2 = `
 #      N O O B A A      # 
 `
 
+//Run runs
```
Comment (guymguym) [inline pkg/cli/cli.go]: priceless comment! :)
